Repository republik/plattform, pull requests merged in 2023-02, with the labels that each got.

#354 fix(republik-crowdfundings): allow only some membership types to receive a reward
  packages/backend-modules/republik-crowdfundings/lib/futureCampaignSenderReward.js
Labels: app: api

#356 fix(future-campaign): fix dark-mode flickering
  apps/www/components/FutureCampaign/FutureCampaignPage.tsx
  apps/www/pages/5-jahre-republik/[code].tsx
Labels: app: www

#365 Admin-Tool: Magic Links as Section
  apps/admin/components/Users/Links.js
  apps/admin/components/Users/Memberships/index.js
  apps/admin/pages/users/[userId].js
Labels: app: admin

#366 fix(Front): headline margins
  packages/styleguide/src/components/TeaserFront/ImageHeadline.js
  packages/styleguide/src/components/TeaserFront/SplitHeadline.js
  packages/styleguide/src/components/TeaserFront/TypoHeadline.js
Labels: package: styleguide

#367 fix(discussions): check member role separatly
  packages/backend-modules/discussions/graphql/resolvers/Discussion/userCanComment.js
Labels: app: api

#362 chore: update turbo to v1.7.4
  package.json
  turbo.json
  yarn.lock
Labels: maintenance

#332 chore(api): update jsonwebtoken to 9.0.0
  packages/backend-modules/auth/package.json
  yarn.lock
Labels: app: api, maintenance

#371 feat(voting): add filter to query value char length for Text questions
  packages/backend-modules/search/lib/indices/questionnaireSubmissions.js
  packages/backend-modules/search/lib/inserts/questionnairesubmission.js
  packages/backend-modules/voting/graphql/schema-types.js
  packages/backend-modules/voting/lib/Submission.js
Labels: app: api
